-- a simple lua program that calculates how much fuel the user needs to pay
-- Alexander Walford 2022

function ClearScreen()
    -- I hate having to write it like this, but it's because of the way that OC works..
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
end

function Start()
    ClearScreen()
    total = 0
    fueliumprice = 30
    print("FUEL PAYMENT SYSTEM")
    print("Please enter your username:")
    user = io.read()
    print("")
    print("Please enter the number of your pump:")
    pump = io.read()
    print("")
    print("What % of fuel did you use? (don't add the %)")
    amount = io.read()
    print("")
    print("OK")
    payment = amount * fueliumprice
    print("")
    print(user .. ", your total is " .. payment .. "WB from pump " .. pump .. ".")
    print("Does this look correct? (y/n)")
    response = io.read()
    if (response == "y")
    then
        print("")
        print("")
        print("Great! Please enter your currency into the dropper to your left.")
        print("Once you have done this, please hit enter.")
        print("")
        io.read()
        -- add text to the file
        local file,err = io.open("sales.txt",'w')
        if file then     
        file:write("Username:" .. user .. "|Pump ID:" .. pump .. "|Payment:" .. payment)
        file:close()
        else
            print("error:", err)
        end
        print("Thank you for doing business with us, you may now leave.")
        print("")
        print("Press enter to continue..")
        io.read()
        Start()
    else
        print("")
        print("")
        print("OK, let's try again. Press enter to continue..")
        io.read()
        Start()
    end
end

Start()